# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c555f8c8a1536a3f4cc1f83c6e63a8f313f38790e91a7d24751dd86c384a69169246e57e01b5b74e4d1ea8f11da12e7c0cc40fb3d13cb60f46915b60e93b51bf

test:
  secret_key_base: 851d6058738d1c0bfa42bc8918daf0ba6d4a361864a60f182f19692e14ed633efdcae5d4d8c7b0f3292e47a021868745e70b18dd8d22cca9f634b07dbfeee507

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
